#!/bin/bash

bleachbit -c adobe_reader.cache
bleachbit -c adobe_reader.mru
bleachbit -c adobe_reader.tmp
bleachbit -c amsn.cache
bleachbit -c amsn.chat_logs
bleachbit -c amule.logs
bleachbit -c amule.tmp
bleachbit -c apt.autoclean
bleachbit -c apt.autoremove
bleachbit -c apt.clean
bleachbit -c apt.package_lists
bleachbit -c audacious.cache
bleachbit -c audacious.log
bleachbit -c audacious.mru
bleachbit -c bash.history
bleachbit -c beagle.cache
bleachbit -c beagle.index
bleachbit -c beagle.logs
bleachbit -c chromium.cache
bleachbit -c chromium.cookies
bleachbit -c chromium.current_session
bleachbit -c chromium.dom
bleachbit -c chromium.form_history
bleachbit -c chromium.history
bleachbit -c chromium.passwords
bleachbit -c chromium.search_engines
bleachbit -c chromium.vacuum
bleachbit -c d4x.history
bleachbit -c deepscan.backup
bleachbit -c deepscan.ds_store
bleachbit -c deepscan.thumbs_db
bleachbit -c deepscan.tmp
bleachbit -c easytag.history
bleachbit -c easytag.logs
bleachbit -c elinks.history
bleachbit -c emesene.cache
bleachbit -c emesene.logs
bleachbit -c epiphany.cache
bleachbit -c epiphany.cookies
bleachbit -c epiphany.dom
bleachbit -c epiphany.passwords
bleachbit -c epiphany.places
bleachbit -c evolution.cache
bleachbit -c exaile.cache
bleachbit -c exaile.downloaded_podcasts
bleachbit -c exaile.log
bleachbit -c filezilla.mru
bleachbit -c firefox.backup
bleachbit -c firefox.cache
bleachbit -c firefox.cookies
bleachbit -c firefox.crash_reports
bleachbit -c firefox.dom
bleachbit -c firefox.download_history
bleachbit -c firefox.forms
bleachbit -c firefox.passwords
bleachbit -c firefox.session_restore
bleachbit -c firefox.site_preferences
bleachbit -c firefox.url_history
bleachbit -c firefox.vacuum
bleachbit -c flash.cache
bleachbit -c flash.cookies
bleachbit -c gedit.recent_documents
bleachbit -c gftp.cache
bleachbit -c gftp.logs
bleachbit -c gimp.tmp
bleachbit -c gl-117.debug_logs
bleachbit -c gnome.run
bleachbit -c gnome.search_history
bleachbit -c google_chrome.cache
bleachbit -c google_chrome.cookies
bleachbit -c google_chrome.dom
bleachbit -c google_chrome.form_history
bleachbit -c google_chrome.history
bleachbit -c google_chrome.passwords
bleachbit -c google_chrome.search_engines
bleachbit -c google_chrome.session
bleachbit -c google_chrome.vacuum
bleachbit -c google_earth.temporary_files
bleachbit -c google_toolbar.search_history
bleachbit -c gpodder.cache
bleachbit -c gpodder.vacuum
bleachbit -c gwenview.recent_documents
bleachbit -c hexchat.logs
bleachbit -c hippo_opensim_viewer.cache
bleachbit -c hippo_opensim_viewer.logs
bleachbit -c java.cache
bleachbit -c journald.clean
bleachbit -c kde.cache
bleachbit -c kde.recent_documents
bleachbit -c kde.tmp
bleachbit -c konqueror.cookies
bleachbit -c konqueror.current_session
bleachbit -c konqueror.url_history
bleachbit -c libreoffice.cache
bleachbit -c libreoffice.history
bleachbit -c liferea.cache
bleachbit -c liferea.cookies
bleachbit -c liferea.vacuum
bleachbit -c links2.history
bleachbit -c midnightcommander.history
bleachbit -c miro.cache
bleachbit -c miro.logs
bleachbit -c nautilus.history
bleachbit -c nexuiz.cache
bleachbit -c octave.history
bleachbit -c openofficeorg.cache
bleachbit -c openofficeorg.recent_documents
bleachbit -c opera.cache
bleachbit -c opera.cookies
bleachbit -c opera.current_session
bleachbit -c opera.dom
bleachbit -c opera.download_history
bleachbit -c opera.passwords
bleachbit -c opera.search_history
bleachbit -c opera.url_history
bleachbit -c pidgin.cache
bleachbit -c pidgin.logs
bleachbit -c realplayer.cookies
bleachbit -c realplayer.history
bleachbit -c realplayer.logs
bleachbit -c recoll.index
bleachbit -c rhythmbox.cache
bleachbit -c rhythmbox.history
bleachbit -c screenlets.logs
bleachbit -c seamonkey.cache
bleachbit -c seamonkey.chat_logs
bleachbit -c seamonkey.cookies
bleachbit -c seamonkey.download_history
bleachbit -c seamonkey.history
bleachbit -c secondlife_viewer.Cache
bleachbit -c secondlife_viewer.Logs
bleachbit -c skype.chat_logs
bleachbit -c skype.installers
bleachbit -c sqlite3.history
bleachbit -c system.cache
bleachbit -c system.clipboard
bleachbit -c system.custom
bleachbit -c system.desktop_entry
bleachbit -c system.free_disk_space
bleachbit -c system.localizations
bleachbit -c system.memory
bleachbit -c system.recent_documents
bleachbit -c system.rotated_logs
bleachbit -c system.tmp
bleachbit -c system.trash
bleachbit -c thumbnails.cache
bleachbit -c thunderbird.cache
bleachbit -c thunderbird.cookies
bleachbit -c thunderbird.index
bleachbit -c thunderbird.passwords
bleachbit -c thunderbird.vacuum
bleachbit -c transmission.blocklists
bleachbit -c transmission.history
bleachbit -c transmission.torrents
bleachbit -c tremulous.cache
bleachbit -c vim.history
bleachbit -c vlc.mru
bleachbit -c vuze.backup_files
bleachbit -c vuze.cache
bleachbit -c vuze.logs
bleachbit -c vuze.tmp
bleachbit -c warzone2100.logs
bleachbit -c wine.tmp
bleachbit -c winetricks.temporary_files
bleachbit -c x11.debug_logs
bleachbit -c xine.cache
bleachbit -c yum.clean_all
bleachbit -c yum.vacuum
