import os

os.system("sudo rm -rf ~/config")
os.system("mkdir ~/config")
user = input("user:\n")
os.system("sudo apt remove docker-desktop")
os.system("sudo apt purge docker-desktop")
os.system("sudo rm -rf ~/.docker")
os.system("sudo apt remove docker docker-engine docker.io containerd runc")
os.system("sudo apt update")
os.system("sudo apt install apt-transport-https ca-certificates curl software-properties-common gnupg2")
os.system("curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg")
os.system("echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu noble stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null")
os.system("sudo apt update")
os.system("sudo apt-get install docker-ce docker-ce-cli containerd.io")
os.system("curl -fsSL https://nvidia.github.io/libnvidia-container/gpgkey | sudo gpg --dearmor -o /usr/share/keyrings/nvidia-container-toolkit-keyring.gpg && curl -s -L https://nvidia.github.io/libnvidia-container/stable/deb/nvidia-container-toolkit.list | sed 's#deb https://#deb [signed-by=/usr/share/keyrings/nvidia-container-toolkit-keyring.gpg] https://#g' | sudo tee /etc/apt/sources.list.d/nvidia-container-toolkit.list")
os.system("sudo apt update")
os.system("export NVIDIA_CONTAINER_TOOLKIT_VERSION=1.18.2-1 sudo apt install nvidia-container-toolkit=${NVIDIA_CONTAINER_TOOLKIT_VERSION} nvidia-container-toolkit-base=${NVIDIA_CONTAINER_TOOLKIT_VERSION} libnvidia-container-tools=${NVIDIA_CONTAINER_TOOLKIT_VERSION} libnvidia-container1=${NVIDIA_CONTAINER_TOOLKIT_VERSION}")
os.system(f"""sudo docker run --runtime=nvidia --gpus all -d --name ersatztv -e TZ=America/Chicago -p 80:8409 -v /home/{user}/Videos/Movies:/media/movies:ro -v /home/{user}/Videos/TV:/media/tv:ro -v /home/{user}/Music:/media/music:ro -v /home/{user}/config:/config --restart always ghcr.io/ersatztv/ersatztv""")
