# To run: git clone https://github.com/Invizabel/Scripts && cd Scripts/Setup && sudo python3 install_mastodon.py

import os

# official Mastodon docs recommends using either Ubuntu LTS or Debian (https://docs.joinmastodon.org/admin/prerequisites/)
domain_name = input("domain name: ")
os.system("apt update && apt upgrade -y")
os.system("apt install fail2ban ufw curl wget gnupg lsb-release ca-certificates -y")
os.system("ufw allow ssh && ufw allow http && ufw allow https && ufw enable")
os.system("curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | gpg --dearmor -o /etc/apt/keyrings/nodesource.gpg")
os.system('echo "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_20.x nodistro main" | tee /etc/apt/sources.list.d/nodesource.list')
os.system("wget -O /usr/share/keyrings/postgresql.asc https://www.postgresql.org/media/keys/ACCC4CF8.asc")
os.system("apt update && apt install imagemagick ffmpeg libvips-tools libpq-dev libxslt1-dev file git protobuf-compiler pkg-config autoconf bison build-essential libssl-dev libyaml-dev libreadline-dev zlib1g-dev libffi-dev libgdbm-dev nginx nodejs redis-server postgresql certbot python3-certbot-nginx libidn-dev libicu-dev libjemalloc-dev -y")
os.system("corepack enable")
os.system("adduser --disabled-password mastodon")
os.system("exit")
os.system('sudo -u postgres psql -c "CREATE USER mastodon CREATEDB;"')
os.system("su - mastodon")
os.system("git clone https://github.com/mastodon/mastodon.git live && cd live")
os.system("git checkout $(git tag -l | grep '^v[0-9.]*$' | sort -V | tail -n 1)")
os.system("git clone https://github.com/rbenv/rbenv.git ~/.rbenv")
os.system('echo \'export PATH="$HOME/.rbenv/bin:$PATH"\' >> ~/.bashrc')
os.system('echo \'eval "$(rbenv init -)"\' >> ~/.bashrc')
os.system("source ~/.bashrc")
os.system('git clone https://github.com/rbenv/ruby-build.git "$(rbenv root)"/plugins/ruby-build')
os.system("RUBY_CONFIGURE_OPTS=--with-jemalloc rbenv install")
os.system("bundle config deployment 'true'")
os.system("bundle config without 'development test'")
os.system("bundle install")
os.system("yarn install")
os.system("RAILS_ENV=production bin/rails mastodon:setup")
os.system("exit")
# This step deviates from the official docs, this will auto config the ssl cert for you in nginx
os.system("cp /home/mastodon/live/dist/nginx.conf /etc/nginx/sites-available/mastodon")
os.system("ln -s /etc/nginx/sites-available/mastodon /etc/nginx/sites-enabled/mastodon")
os.system("rm /etc/nginx/sites-enabled/default")
os.system("nginx -t")
os.system("systemctl reload nginx")
os.system(f"certbot --nginx -d {domain_name} --non-interactive --agree-tos -m admin@{domain_name}")
os.system("systemctl reload nginx")
# end of nginx ssl part
os.system("chmod o+x /home/mastodon")
os.system("systemctl restart nginx")
os.system("cp /home/mastodon/live/dist/mastodon-*.service /etc/systemd/system/")
os.system("systemctl daemon-reload")
os.system("systemctl enable --now mastodon-web mastodon-sidekiq mastodon-streaming")
os.system("reboot")
